### ISSUE TITLE
🐞 Bug Report: auto selecting icon in firefox not working

### ISSUE THREAD

**Issue by roohino** [tisfeng/Easydict#166]
### Please confirm the following:

- [X] I have carefully read the [README](https://github.com/tisfeng/Easydict#readme)
- [X] I have searched through the [issues](https://github.com/tisfeng/Easydict/issues) page but couldn't find a solution.(Including issue that has been closed)
- [X] Easydict has been upgraded to the latest version.

### Problem description

Hello
I really liked this app, but I have got problem. in Firefox when I select text mini icon not shows. in safari and chrome every thing is fine.

### Reproduction steps

in firefox When I select the text hover icon not working

### Expected result

I wanna shows hover icon after I selected a text

### Are you willing to submit a PR to fix this issue?

- [ ] I'm willing to submit a PR!

**Comment by tisfeng** [comment]
@roohino Hi

Please make sure that you have enabled the auxiliary function permission for Easydict.

Sometimes, due to system bugs, even if you turn on accessibility, it won't work properly, so you need to remove the option and manually click the + in the bottom-left corner to re-add Easydict.

In addition, Safari and Chrome also support AppleScript to fetch words in addition to system Accessibility, but unfortunately Firefox doesn't support it.

<img width="751" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/2aa7fa0e-400a-4304-8375-43d74da84b99">

**Comment by moroumo** [comment]
Got the similar issue, EasyDict doesn't work for firefox. Following other similar fixing, I added firefox bundle id `org.mozilla.firefox` to `kAXErrorAttributeUnsupported` and enabled  the setting: `Force get selected text .... (Experimental)`, it works now.

Let me know if you prefer to fixing it by yourself or I can send a PR. @tisfeng

Good tool, thank you.

**Comment by tisfeng** [comment]
@moroumo Of course, you can submit PRs to the dev branch.

Firefox is one of those special apps that works fine on my computer, but not on some users' computers, like yours 🥲

**Comment by tisfeng** [comment]
Hi, the [2.0.1](https://github.com/tisfeng/Easydict/releases/tag/2.0.1) version has fixed the issue.

**Comment by truebit** [comment]
firefox 129.0.2 又不行了。好像是easydict更新后的问题

**Comment by tisfeng** [comment]
请尝试开启【强制划词】 https://github.com/tisfeng/Easydict/issues/640#issuecomment-2286322490
