### ISSUE TITLE
dev: SwiftUI Setting - no alert while enabling hide icon in menu bar

### ISSUE THREAD

**Issue by CanglongCl** [tisfeng/Easydict#345]
@tisfeng Could you please help me check if there is anything else missing? I'll handle it later.

**Comment by tisfeng** [comment]
Currently, just show alert message if user try to hide menu icon.

Later on maybe we should use code to check if the user has set a shortcut to open Easydict, and if no shortcut is set, then we should not allow the menu icon to be hidden, otherwise it will result in the user not being able to open Easydict again.

<img width="617" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/0a5abeac-b061-4f41-ab5f-3ce10ad06b7e">

**Comment by tisfeng** [comment]
@AkaShark Can you do this feature?

1. Determine if the user has set shortcuts for input translation or selection translation. If not, do not allow hiding the menu bar icon and display a prompt message.
2. If so, allow hiding the menu bar icon and inform the user how to show it again, similar to the image above.

**Comment by AkaShark** [comment]
> @AkaShark Can you do this feature?
> 
> 1. Determine if the user has set shortcuts for input translation or selection translation. If not, do not allow hiding the menu bar icon and display a prompt message.
> 2. If so, allow hiding the menu bar icon and inform the user how to show it again, similar to the image above.

okay
