### ISSUE TITLE
"Launch at login" doesn't work

### ISSUE THREAD

**Issue by simonbcn** [tisfeng/Easydict#646]
### Please confirm the following:

- [x] Be sure to check out [FAQ](https://github.com/tisfeng/Easydict/wiki/FAQ)
- [X] I have carefully read the [README](https://github.com/tisfeng/Easydict#readme)
- [X] I have searched through the [issues](https://github.com/tisfeng/Easydict/issues) page but couldn't find a solution.(Including issue that has been closed)
- [X] Easydict has been upgraded to the [latest version](https://github.com/tisfeng/Easydict/releases)
- [X] I understand and agree to the above, and understand that the project maintainer has limited energy, **issues that do not follow the rules may be ignored or closed directly**

### Problem description

When I activate "_launch at login_" it doesn't really add it to the login items or start it when I reboot the system.

### Is the issue consistently reproducible?

Reproducible

### Steps to Reproduce

Read problem description

### Screenshot

![Captura de pantalla 2024-08-16 a las 10 07 11](https://github.com/user-attachments/assets/ecacb7ec-d85a-419a-82be-2fab3c64e4fa)

### Runtime log

[com.izual.Easydict 2024-08-16--07-54-56-460.log](https://github.com/user-attachments/files/16634677/com.izual.Easydict.2024-08-16--07-54-56-460.log)

### Expected result

It should add _easydict_ to the login items on macOS.

### Device type and OS version

Apple M2, macOS 14.5

### Are you willing to submit a PR to fix this issue?

- [ ] I'm willing to submit a PR to fix this issue

**Comment by tisfeng** [comment]
Hello, please check the system settings - Privacy and Security - Automation, and ensure that Easydict has System Events permissions https://github.com/tisfeng/Easydict/issues/625#issuecomment-2260739495 .

If it already exists, try turning it off, then re-enable it, and then reopen the "Launch at login" item in Easydict.

**Comment by simonbcn** [comment]
But this should not be so. Why doesn't it ask for permissions from the application itself when you activate that option?

**Comment by Jerry23011** [comment]
Because Easydict uses Apple Script with launch at login

https://github.com/tisfeng/Easydict/blob/f18eb571e324dacb6b96ff095248c5e3071ff105/Easydict/Swift/Feature/Configuration/Configuration.swift#L588

> But this should not be so. Why doesn't it ask for permissions from the application itself when you activate that option?

This is a good point. Perhaps we can consider using other ways to implement launch at login. @tisfeng 

This [package](https://github.com/sindresorhus/LaunchAtLogin-Modern) works well.

**Comment by tisfeng** [comment]
Thanks for the suggestion, it does need improvement here.

Using AppleScript for launch at login is not a good choice, it was just a solution for https://github.com/tisfeng/Easydict/issues/64 and https://github.com/tisfeng/Easydict/issues/79 .

Since we only support macOS 13+, it's time to switch to `SMAppService`.

[LaunchAtLogin-Modern](https://github.com/sindresorhus/LaunchAtLogin-Modern) is a good option, I'll take a look at it later.

**Comment by tisfeng** [comment]
This issue will be fixed in next release.

**Comment by tisfeng** [comment]
Hello, the [2.9.0](https://github.com/tisfeng/Easydict/releases/tag/2.9.0) version has fixed this issue.
