### ISSUE TITLE
dev: So sad to see you dropped the support for older version of macOS

### ISSUE THREAD

**Issue by aayushkrm** [tisfeng/Easydict#674]
I have macbook pro 2015 running macOS Montrey 12, it runs easydict 2.7.2 but I won't be able to update to the 2.8.1 ;(

**Comment by tisfeng** [comment]
Sorry, since none of our members are using lower versions of macOS, it is difficult to debug and maintain issues on these old versions https://github.com/tisfeng/Easydict/issues/251.

Additionally, since we have used many new APIs from SwiftUI, which require macOS 13.0 or higher, we have to abandon support for older versions 😥
